# Generated by Django 6.0.6 on 2026-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='book_qr/'),
        ),
    ]
