# Generated by Django 6.0.6 on 2026-06-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_issuebook_fine_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={'ordering': ['id']},
        ),
    ]
