# Generated by Django 6.0.6 on 2026-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(default='Not Provided')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('department', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
